plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.74'
}
apply from: '../minecraft_gradle_tools/src/mc1211/ECDependencies.gradle'

version = "${mod_version}"
group = "com.userofbricks.${mod_id}"

repositories {
    repos()
    mavenCentral()
    maven {
        url = "https://maven.tamaized.com/releases"
    }
}

base {archivesName = "${mod_id}-${minecraft_version}"}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

mcrunsModdev(mod_id)

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation "team-twilight:twilightforest:${twilight_forest_version}:universal"

    expanded_combat()
    cloth_config()
    curiosAll()
    jei()
    //better_combat()
}
var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    var replaceProperties = [
            minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
            neo_version: neo_version, neo_version_range: neo_version_range,
            loader_version_range: loader_version_range,
            mod_id : mod_id,
            mod_name : mod_name,
            mod_license : mod_license,
            mod_version : mod_version,
            mod_authors : mod_authors,
            mod_description : mod_description,
    ]

    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.resources.srcDir generateModMetadata
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
neoForge.ideSyncTask generateModMetadata

// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
