
modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

#issueTrackerURL="https://github.com/userofbricks/Expanded-Combat/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#displayURL="https://www.curseforge.com/minecraft/mc-mods/expanded-combat"
#logoFile="expanded_combat_logo.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="curios"
mandatory=true
versionRange="[${curios_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cloth_config"
mandatory=true
versionRange="[${cloth_config_api_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="twilightforest"
mandatory=true
versionRange="[${twilight_forest_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="expanded_combat"
mandatory=true
versionRange="[${expanded_combat_version},)"
ordering="BEFORE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="bettercombat"
mandatory=false
versionRange="[${better_combat_version},)"
ordering="NONE"
side="BOTH"